version: '2.1'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
    - "27017:27017"
    volumes:
      - mongovolume:/data/db
  mongo-express:
      image: mongo-express
      restart: always
      ports:
        - "8081:8081"
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example

  rabbit:
    hostname: rabbit
    build:
      context: ./rabbit
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
  nepomoika:
    build:
      context: ./vue
      dockerfile: Dockerfile
    ports:
      - "88:80"
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8090:5000"
    depends_on:
      - postgres
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: ["python", "./main.py"]
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8099:5000"
    depends_on:
      - postgres
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USERS_DB=${POSTGRES_USERS_DB}
    command: ["python", "./main.py"]

  postgres:
    image: postgres:10
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
      - db_data_back:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_DB},${POSTGRES_USERS_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  db_data_back:
  mongovolume:
# psql -h localhost -p 5432 -U back -d store
# psql -h localhost -p 5432 -U back -d users