version: '2.1'

services:
  nepomoika:
    build:
      context: ./vue
      dockerfile: Dockerfile
    ports:
      - 88:80
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:5000
    depends_on:
      - postgres
#    network_mode: "host"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
#      - PORT=5020
#      - API_ADDRESS=test
#      - STATUS_ADDRESS=status
#      - RESULT_ADDRESS=result
    command: ["python", "./main.py"]

  postgres:
    restart: always
    image: postgres:10
#    volumes:
#      - db_data_back:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

#volumes:
#  db_data_back:

# psql -h localhost -p 5432 -U back -d back